# LibreLane configuration file

DESIGN_NAME: tt_um_example
VERILOG_FILES: dir::../src/tt_um_example.sv
CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Default size
DIE_AREA: [0, 0, 202.08, 154.98]
FP_DEF_TEMPLATE: dir::def/tt_block_1x1_pgvdd.def

# Default size
DIE_AREA: [0, 0, 202.08, 313.74]
FP_DEF_TEMPLATE: dir::def/tt_block_1x2_pgvdd.def

# Don't use power rings or TopMetal layers
FP_PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true
