# LibreLane configuration file

DESIGN_NAME: heichips25_template
VERILOG_FILES: 
- dir::../src/heichips25_template.sv 
- dir::../src/snitch/src/riscv_instr.sv
- dir::../src/snitch/src/snitch.sv
- dir::../src/snitch/src/snitch_lsu.sv
- dir::../src/snitch/src/snitch_pkg.sv
- dir::../src/snitch/src/snitch_regfile_ff.sv
- dir::../src/deps/common_cells/src/rr_arb_tree.sv
- dir::../src/deps/common_cells/src/spill_register.sv
- dir::../src/deps/common_cells/src/spill_register_flushable.sv
- dir::../src/deps/common_cells/src/lzc.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true
