# LibreLane configuration file

DESIGN_NAME: heichips25_snitch_wrapper
VERILOG_FILES: 
- dir::../src/heichips25_snitch_wrapper.sv 
- dir::../src/snitch/src/riscv_instr.sv
- dir::../src/snitch/src/snitch.sv
- dir::../src/snitch/src/snitch_lsu.sv
- dir::../src/snitch/src/snitch_pkg.sv
- dir::../src/snitch/src/snitch_regfile_ff.sv
- dir::../src/cf_math_pkg.sv
- dir::../src/rr_arb_tree.sv
- dir::../src/spill_register.sv
- dir::../src/spill_register_flushable.sv
- dir::../src/lzc.sv
- dir::snitch_logo.v

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6
#ERROR_ON_SYNTH_CHECKS: false
#ERROR_ON_DISCONNECTED_PINS: false
# Absolute die size
FP_SIZING: absolute


 
# Small DEF template
#DIE_AREA: [0, 0, 500, 200]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
DIE_AREA: [0, 0, 500, 415]
FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: Metal5

# Enable for better SystemVerilog support
USE_SLANG: true

#OUR OPTIMIZATIONS
GRT_ALLOW_CONGESTION: true
PL_TARGET_DENSITY_PCT: 54
SYNTH_STRATEGY: AREA 1
#SYNTH_ABC_USE_MFS3: true
PL_TIME_DRIVEN: true
#SYNTH_HIERARCHY_MODE: keep
SYNTH_AUTONAME: true
PL_RESIZER_SETUP_SLACK_MARGIN: 0.2
PL_RESIZER_SETUP_MAX_BUFFER_PCT: 80
GRT_RESIZER_SETUP_MAX_BUFFER_PCT: 80
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.1

# Probably the Cause of Met2 error

PDN_OBSTRUCTIONS:
 - [TopMetal1, 318, 0, 466, 415]
 

 

